name: Build Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        workingdirectory: ./exampleSite
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: get theme (epic hack)
        workingdirectory: ./exampleSite
        run: |
          git clone https://github.com/Odyssey346/hugo-theme-m1n1m4l themes/m1n1m4l
      - name: Setup Hugo
        workingdirectory: ./exampleSite
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        workingdirectory: ./exampleSite
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        workingdirectory: ./exampleSite
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public