name: Build Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exampleSite
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: get theme (epic hack)
        run: |
          git clone https://github.com/Odyssey346/hugo-theme-m1n1m4l themes/m1n1m4l
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Ls
        run: ls --color

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: gh-pages # The branch the action should deploy to.
            folder: exampleSite/public # The folder the action should deploy.
            commit-message: Successfully built
            clean: true
            single-commit: false